name: Deploy Frontend & Backend with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # ✅ STEP 1: Start Deployment (will show in GitHub "Deployments" tab)
      - name: Create GitHub Deployment
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      # ✅ STEP 2: Deploy your app (docker-compose)
      - name: Build and run containers
        run: |
          docker-compose up -d --build

      # ✅ STEP 3: Mark deployment as success
      - name: Mark Deployment as Success
        uses: bobheadxi/deployments@v0.6.0
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: success
          env: production
