name: Deploy Frontend & Backend with Docker Compose

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ensure Docker Compose is available
        run: docker-compose --version

      - name: Build and run containers
        run: docker-compose up -d --build

      - name: List running containers
        run: docker ps -a

      - name: Mark Deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          description: Deployed frontend and backend containers 🚀

